apiVersion: v1
kind: Service
metadata:
  name: menu
  namespace: ordering
  labels:
    app.kubernetes.io/name: menu
    app.kubernetes.io/part-of: ordering-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: menu
  ports:
    - name: http
      port: 80
      targetPort: http
